-- USE worksuite;

INSERT INTO Role(ROLE_NAME, ROLE_VALUE) VALUES("SuperAdmin", 1);
INSERT INTO Role(ROLE_NAME, ROLE_VALUE) VALUES("Admin", 2);
INSERT INTO Role(ROLE_NAME, ROLE_VALUE) VALUES("Member", 3);

